name: Deploy Cloud Run

on:
  push:
    branches:
      - main
    paths-ignore:
      - "functions/**"
      - ".vscode/**"
      - ".github/workflows/deploy-cloud-functions.yml"
      - "README.md"
      - "tsconfig.json"
      - ".prettierrc.js"
      - ".eslintrc.js"

jobs:
  build-deploy:
    name: Deploy Cloud Run
    runs-on: ubuntu-latest

    env:
      REGION: asia-northeast1
      IMAGE: gcr.io/${{ secrets.GCP_CI_PROJECT_ID }}/corona-calendar:${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_CI_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_CI_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_CI_SERVICE_ACCOUNT_KEY }}

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker build . -t $IMAGE

      - name: Push the docker image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy foobar \
              --image $IMAGE \
              --project $GCP_PROJECT \
              --region $GCP_REGION \
              --platform managed \
              --quiet
