name: Deploy Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest

    env:
      REGION: us-central1

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: actions/cache@v2
        with:
          path: 'functions/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: corona-weekly-calendar
          service_account_email: ci-deploy@corona-weekly-calendar.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_CI_SERVICE_ACCOUNT_KEY }}

      - name: Deploy Functions
        run: |
          cd functions
          yarn
          yarn deploy
