name: Deploy Cloud Run

on:
  release:
    types: [created]

jobs:
  build-deploy:
    name: Deploy Cloud Run
    runs-on: ubuntu-20.04

    env:
      IMAGE: gcr.io/${{ secrets.GCP_CI_PROJECT_ID }}/corona-calendar:${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_CI_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_CI_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_CI_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker build . -t $IMAGE

      - name: Push the docker image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy corona-calendar \
              --image $IMAGE \
              --project ${{ secrets.GCP_CI_PROJECT_ID }} \
              --region asia-northeast1 \
              --platform managed \
              --quiet
