name: Deploy Cloud Functions

on:
  push:
    branches:
      - main
    paths:
      - "functions/**"
      - "!functions/**.test.ts"

jobs:
  build-deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest

    env:
      REGION: us-central1

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get yarn cache directory path
        id: dir-path-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.dir-path-yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('functions/yarn.lock') }}
          restore-keys: |
              ${{ runner.os }}-yarn-

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_CI_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_CI_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_CI_SERVICE_ACCOUNT_KEY }}

      - name: Install dependency  # --prefer-offlineをつけることで、存在する場合はキャッシュを使用する
        run: |
          cd functions
          yarn --prefer-offline

      - name: Test
        run: |
          cd functions
          yarn test:ci

      - name: Deploy Functions
        run: |
          cd functions
          yarn deploy
