name: CI(Lint and Test)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  lint-and-test-app:
    runs-on: ubuntu-latest
    name: Run ESLint and Prettier / Run Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependency  # --prefer-offlineをつけることで、存在する場合はキャッシュを使用する
        run: |
          yarn --prefer-offline
      
      - name: Lint
        run: |
          yarn fix

      - name: Test
        run: |
          yarn test:ci

  lint-and-test-cloud-functions:
    runs-on: ubuntu-latest
    working-directory: functions
    name: Run ESLint and Prettier / Run Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Install dependency  # --prefer-offlineをつけることで、存在する場合はキャッシュを使用する
        run: |
          yarn --prefer-offline

      - name: Lint
        run: |
          yarn fix

      - name: Test
        run: |
          yarn test:ci

