name: CI(Lint)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  lint-and-test-app:
    runs-on: ubuntu-latest
    name: App (Run ESLint and Prettier)
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependency  # --prefer-offlineをつけることで、存在する場合はキャッシュを使用する
        run: |
          yarn --prefer-offline
      
      - name: Lint
        run: |
          yarn fix

  lint-and-test-cloud-functions:
    runs-on: ubuntu-latest
    name: Cloud Functions (Run ESLint and Prettier)
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Install dependency  # --prefer-offlineをつけることで、存在する場合はキャッシュを使用する
        run: |
          yarn --prefer-offline
        working-directory: ./functions

      - name: Lint
        run: |
          yarn fix
        working-directory: ./functions


